name: Staging Deployment CI

on:
  push:
    branches: ['master']  

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: staging   

      - name: Create Pull Request        
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-staging
