name: Staging Deployment CI

on:
  push:
    branches: ['master']  

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: staging
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master

      - name: Create Pull Request        
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-staging
